### PR TITLE
Add tox support to cram workspace

### PR DESCRIPTION
**Pull request by Nicoretti**
Hi Brodie,

I hope you are doing well.

I am a huge fan of cram and recently I was digging more into it. I feel there is still some more potential
in cram (Don't get me wrong, the current state is already great!).

First thing I usually do when I pickup a project, is try to getting it to build and get the tests running.
While doing this for cram I figured, the testing/verification could be simplified by using tox.
For example the test matrix python-version(s) + shell(s).

I think there would be even more potential in using tox, but it most likely would
break compatibility with the Makefile workflow.

When I created the PR I also realised there are a similar PRs #22 #23 which may be closed in case this one will make it in.

I also have dropped support/builds in travis CI for all unsupported python versions.

Let me know what you think about it.

Best
Nico

### CODE REVIEW

**Comment by aiiie** [comment]
Is it still possible to use Travis for free? My interaction with their support team leads me to think not.

Is there another service that could be used for builds?

**Comment by aiiie** [comment]
Maybe GitHub Actions would suffice?: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

**Comment by Nicoretti** [comment]
Hi @brodie,

I just checked, seems you are right. It looks like that you have some free tokens for oss repos, but generally the
payment structure is not very transparent. I think GitHub Actions would be a legit alternative.

**Comment by Nicoretti** [comment]
If you are interested in having it run with GitHub Action(s) I can look into it tomorrow

**Comment by Nicoretti** [comment]
@brodie migrated a basic version of the test setup to GitHub, with a couple of small adjustments in the setup (see commits above) it seems to work just fine (https://github.com/Nicoretti/cram/actions/runs/1629899894)

**Comment by kynan** [comment]
I suggest switching to GitHub actions, which allows running tests across Linux, MacOS and Windows.

**Pull request closed without merging**
